# MOVING AVERAGE

In [16]:
import numpy as np


n=int(input())
a=list(map(int,input().split()))

a=np.array(a)
k=int(input())

13
3 5 7 2 8 10 11 65 72 81 99 100 150
3


In [20]:

for i in range(n-k+1):
    print("y"+str(i)+":  ",int(np.mean(a[i:i+k])))
    

y0:   5
y1:   4
y2:   5
y3:   6
y4:   9
y5:   28
y6:   49
y7:   72
y8:   84
y9:   93
y10:   116


# VANDER MATRIX 

In [22]:
f=np.array([1,2,3])
print(np.vander(f)) # N=len(f) when not specified

[[1 1 1]
 [4 2 1]
 [9 3 1]]
